theme: jekyll-theme-minimal
title: Global Brews, Local Views
description: Analyzing Cross-Country Beer Preferences and Challenging Reviewer Bias
show_downloads: True
navigation:
  - title: Home
    url: /
  - title: Example
    url: example
